version: '3'
services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: biwed_stat_kafka
    restart: "no"
    ports:
      - "9091:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - "kafka"
  zookeeper:
    image: debezium/zookeeper:latest
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:latest
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
  connect:
    build:
      context: debezium-jdbc
      args:
        DEBEZIUM_VERSION: 2.5
    ports:
     - 8083:8083
     - 1976:1976
    links:
     - kafka
     - pg_source
     - pg_sink
    environment:
     - BOOTSTRAP_SERVERS=kafka:29092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=connect_configs
     - OFFSET_STORAGE_TOPIC=connect_offsets
     - STATUS_STORAGE_TOPIC=source_connect_statuses
     - KAFKA_OPTS=-javaagent:/kafka/etc/jmx_prometheus_javaagent.jar=8080:/kafka/etc/config.yml
     - JMXHOST=localhost
     - JMXPORT=1976
  pg_source:
    image: postgres:14
    ports:
     - "5434:5432"
    environment:
     - POSTGRES_USER=postgresuser
     - POSTGRES_PASSWORD=postgrespw
     - POSTGRES_DB=oltp
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
  pg_sink:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=oltp_sink
  prometheus:
    build:
      context: debezium-prometheus
      args:
        PROMETHEUS_VERSION: v2.43.0
    ports:
      - 9090:9090
    links:
      - connect
  grafana:
    build:
      context: debezium-grafana
      args:
        GRAFANA_VERSION: 9.4.7
    ports:
      - 3000:3000
    links:
      - prometheus
    environment:
      - DS_PROMETHEUS=prometheus